object Versions {
            const val RX_JAVA = "3.0.4"
    const val RX_KOTLIN = "3.0.0"
    const val RX_RELAY = "3.0.0"
    const val RETROFIT = "2.9.0"
    const val QUARTZ = "2.3.0"
    const val POSTGRES = "42.2.5"
    const val EXPOSED = "0.24.1"
    const val SHADOW = "4.0.2"
    const val KOTLIN = "1.4.21"
    const val SCRIBE = "6.0.0"
    const val KTLINT_PLUGIN = "9.4.1"
    const val KTLINT = "0.40.0"
    const val OK_HTTP = "4.9.0"
}
